 This file adds Brother Neffs code of checklist and things to be added when making the tables for the competitions


_*NEFF CODE*_ 
* Code
  This hook function will ensure that only one item can be checked at a time
  in a list tagged with =:radio= as the value of the =attr_org= tag.
#+begin_src emacs-lisp :results silent
  (require 'dash)

  (defun check-hook-fn ()
    (when (-contains? (org-element-property
                       :attr_org
                       (org-element-property :parent (org-element-context)))
                      ":radio")
      (save-excursion
        (loop for el in (org-element-property :structure (org-element-context))
              do (goto-char (car el))
              (when (re-search-forward "\\[X\\]" (line-end-position) t)
                (replace-match "[ ]"))))
      (beginning-of-line)
      (re-search-forward "\\[\\s-\\]" (line-end-position) t)
      (replace-match "[X]")))

  (add-hook 'org-checkbox-statistics-hook 'check-hook-fn)
#+end_src

  Code to get and validate chosen list items.
#+begin_src emacs-lisp :results silent
  (require 'cl)
  (require 'org-element)

  (defun org-get-plain-list (name)
    "Get the org-element representation of a plain-list with NAME."
    (catch 'found
      (org-element-map
          (org-element-parse-buffer)
          'plain-list
        (lambda (plain-list)
          (when
              (string= name (org-element-property :name plain-list))
            (throw 'found plain-list))))))

  (defun get-checkbox-list-values (list-name)
    "Return the values of all the checked items in a checkbox list."
    (save-excursion
      (loop for el in (org-element-property
                       :structure
                       (org-get-plain-list list-name))
            if (string= (nth 4 el) "[X]")
            collect (let ((item (buffer-substring (first el) (first (last el)))))
                      (string-match "\\[X\\]\\s-\\(.*\\)$" item)
                      (match-string 1 item)))))

  (defun validate-radio-list (choices)
    "Validates that a just one choice was made then returns
      that choice, otherwise returns an error message."
    (if (= 1 (length choices))
        (first choices) "Invalid or unanswered."))
#+end_src

* Samples
** A Normal Checkbox List
#+name: groceries
  - [X] milk
  - [ ] eggs
  - [X] butter
  - [X] yogurt

** Radio Button Lists
#+attr_org: :radio
#+name: age
  - [ ] --
  - [X] Peewee
  - [ ] Preteen
  - [ ] Junior
  - [ ] Youth
  - [X] Collegiate
  - [ ] Adult
  - [ ] Senior

#+attr_org: :radio
#+name: level
  - [ ] --
  - [ ] Newcomer
  - [ ] Bronze
  - [X] Silver 1
  - [ ] Silver 2
  - [X] Gold 1
  - [ ] Gold 2
  - [ ] Open
  - [ ] Bonus
  - [ ] Novice
  - [ ] Pre-Champion
  - [ ] Champion

* Tests
#+BEGIN_SRC emacs-lisp :results raw
  (setq opl (org-get-plain-list "groceries")
        ans (org-element-property :name opl))
#+END_SRC

#+RESULTS:
groceries
groceries

#+BEGIN_SRC emacs-lisp :results raw
  (get-checkbox-list-values "groceries")
#+END_SRC

#+RESULTS:
(milk butter yogurt)
(milk butter)

#+BEGIN_SRC emacs-lisp :results raw
  (validate-radio-list (get-checkbox-list-values "age"))
#+END_SRC

#+RESULTS:
Invalid or unanswered.
Collegiate

#+BEGIN_SRC emacs-lisp :results raw
  (validate-radio-list (get-checkbox-list-values "level"))
#+END_SRC

#+RESULTS:
Invalid or unanswered.
Gold 1



* -- *BUILD TABLES* --



** :example of table: 
  | Couple | 	A | 	B | 	C | 	D | 	E | 	F | 	G | 	H |
  |--------+-----+-----+-----+-----+-----+-----+-----+-----|
  |    111 |   7 |   7 |   7 |   7 |   7 |     |     |     |
  |    112 |   4 |   6 |   3 |   6 |   4 |     |     |     |
  |    113 |   1 |   5 |   2 |   3 |   5 |     |     |     |
  |    114 |   3 |   3 |   4 |   5 |   1 |     |     |     |
  |    115 |   2 |   1 |   1 |   2 |   2 |     |     |     |
  |    116 |   5 |   4 |   6 |   1 |   3 |     |     |     |
  |    117 |   6 |   2 |   5 |   4 |   6 |     |     |     |


**  _*DanceCompetition*_

Please enter the number of judges needed for the competition
NOTE: if the number does not appear in the list, you may type it in 
      where the '--' indicators are.

#+attr_org: :radio
#+name: number_judges
  - [ ] 3
  - [X] 5
  - [ ] 7
  - [ ] 9
  - [ ] 11
  - [ ] --

#+attr_org: :radio
#+name: number_couples
  - [ ] 3
  - [ ] 5
  - [X] 7
  - [ ] 9
  - [ ] 11
  - [ ] --

#+attr_org: :radiod
#+name: number_dances
  - [ ] 3
  - [X] 5
  - [ ] 7
  - [ ] 9
  - [ ] 11
  - [ ] --

**  _VALIDATE THE INPUT_ 
#+BEGIN_SRC emacs-lisp
  (validate-radio-list (get-checkbox-list-values "number_judges"))
#+END_SRC

#+RESULTS:
: 5
 
#+BEGIN_SRC emacs-lisp
  (validate-radio-list (get-checkbox-list-values "number_couples"))
#+END_SRC

#+RESULTS:
: 7

#+BEGIN_SRC emacs-lisp
  (validate-radio-list (get-checkbox-list-values "number_dances"))
#+END_SRC

#+RESULTS:
: 5


** _SETUP THE VARIABLES_
#+BEGIN_SRC elisp :results value
(setq num_dances (string-to-number (car (get-checkbox-list-values "number_dances"))))
#+END_SRC

#+RESULTS:
: 5

#+BEGIN_SRC elisp :results value 
(symbol-value 'num_dances)
#+END_SRC   

#+RESULTS:
: 5

#+BEGIN_SRC elisp :results value
  (setq num_judges (string-to-number (car (get-checkbox-list-values "number_judges"))))
#+END_SRC

#+RESULTS:
: 5

#+BEGIN_SRC elisp :results value
  (setq num_couples (string-to-number (car (get-checkbox-list-values "number_couples"))))
#+END_SRC

#+name: cha-cha-table
: 7


** TODO _Automate Table_

*** _CONSTRUCT TABLE_ 

#+BEGIN_SRC elisp :results silent 
  (defun header (num-judges)
    (let* ((start ?A) 
           (end (+ start num-judges -1)))
      (list (append '(Couple) (mapcar 'char-to-string (number-sequence start end))))))

  (defun body (num_couples)
    (loop for couple from 0 to num_couples
      collect(list "")))

  (defun build-tables (num_judges num_couples)
    (append(header num_judges)(list 'hline)(body num_couples)))
#+END_SRC

*** _NAME THE DANCE_
#+BEGIN_SRC elisp :results silent
  (setq dance "cha-cha")
#+END_SRC
#+BEGIN_SRC elisp
 (set (intern (concat dance "-table")) (build-tables '(5) 5))
#+END_SRC

#+BEGIN_SRC elisp 
  cha-cha-table
#+END_SRC

#+RESULTS:
| Couple | A | B | C | D | E |
|--------+---+---+---+---+---|
|        |   |   |   |   |   |
|        |   |   |   |   |   |
|        |   |   |   |   |   |
|        |   |   |   |   |   |
|        |   |   |   |   |   |
|        |   |   |   |   |   |
|        |   |   |   |   |   |
|        |   |   |   |   |   |


*** _Name the table for the dance_
#+BEGIN_SRC elisp
  (when (search-backward (format "%c+RESULTS:" ?#) nil t)
    (replace-match (concat "#+name: " (symbol-name 'cha-cha-table)) t))  
#+END_SRC

** TEST FUNCTINOS AREA

#+BEGIN_SRC elisp
(header num_judges)
#+END_SRC

#+name: 
| Couple | A | B | C | D | E |

#+BEGIN_SRC elisp
(body num_couples)
#+END_SRC

#+name: t-name
|   |
|   |
|   |
|   |
|   |
|   |
|   |
|   |




#+BEGIN_SRC elisp
(setq dance "salsa")
#+END_SRC


#+BEGIN_SRC elisp
(setq t-name (set (intern (concat dance "-table")) (build-tables num_judges num_couples)))
#+END_SRC

#+BEGIN_SRC elisp
 salsa-table
#+END_SRC

#+name: 
| Couple | A | B | C | D | E |
|--------+---+---+---+---+---|
|        |   |   |   |   |   |
|        |   |   |   |   |   |
|        |   |   |   |   |   |
|        |   |   |   |   |   |
|        |   |   |   |   |   |
|        |   |   |   |   |   |
|        |   |   |   |   |   |
|        |   |   |   |   |   |

#+name: 
| Couple | A | B | C | D | E |
|--------+---+---+---+---+---|
|        |   |   |   |   |   |
|        |   |   |   |   |   |
|        |   |   |   |   |   |
|        |   |   |   |   |   |
|        |   |   |   |   |   |
|        |   |   |   |   |   |
|        |   |   |   |   |   |
|        |   |   |   |   |   |

#+name: intern-table
| Couple | A | B | C | D | E |
|--------+---+---+---+---+---|
|        |   |   |   |   |   |
|        |   |   |   |   |   |
|        |   |   |   |   |   |
|        |   |   |   |   |   |
|        |   |   |   |   |   |
|        |   |   |   |   |   |
|        |   |   |   |   |   |
|        |   |   |   |   |   |


#+BEGIN_SRC elisp
  (when (search-backward (format "%c+RESULTS:" ?#) nil t)
    (replace-match (concat "#+name: " (symbol-function 'salsa-table)) t))  
#+END_SRC

